version: "3"

services:
  db:
    image: meetanshi18/mysql-app:v1
    build: ./db
  web:
    image: meetanshi18/node-app:v1
    build: ./web
    ports:
      -  "4000:4000"
    depends_on:
      -  db
    restart: on-failure
