version: "3"

services:
  db:
    image: meetanshi18/mysql-app
    build: ./db
  web:
    image: meetanshi18/node-app
    build: ./web
    ports:
      -  "3000:3000"
    depends_on:
      -  db
    restart: on-failure